
name: Saleor Cypress Tests
on: [push]
jobs:
  Cypress-run:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cypress.io
      uses: cypress-io/github-action@v4
      with: 
        start: npm start